# Generated by Django 4.2.30 on 2026-05-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When set, the user completed email verification.', null=True),
        ),
    ]
