# Generated by Django 4.2.30 on 2026-05-13 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licensing', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
        ('storage_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDownload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_snapshot', models.JSONField(default=dict, help_text='Immutable snapshot of DownloadPermission facts at issuance time.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('licensed_track_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_downloads', to='licensing.licensedtracksource')),
                ('storage_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_downloads', to='storage_integration.managedstorageobject')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_downloads', to='catalog.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'downloads_saved_download',
            },
        ),
        migrations.CreateModel(
            name='OfflineLibraryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('saved_download', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_items', to='downloads.saveddownload')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_items', to='catalog.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'downloads_offline_library_item',
            },
        ),
        migrations.CreateModel(
            name='DownloadAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('requested', 'Requested'), ('allowed', 'Allowed'), ('denied', 'Denied'), ('completed', 'Completed'), ('revoked', 'Revoked')], db_index=True, max_length=32)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('licensed_track_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_audit_logs', to='licensing.licensedtracksource')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_audit_logs', to='catalog.track')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'downloads_download_audit_log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ComplianceAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ai_job', 'AI job'), ('subscription', 'Subscription'), ('moderation', 'Moderation'), ('storage', 'Storage'), ('other', 'Other')], db_index=True, max_length=32)),
                ('subject_object_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('subject_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'downloads_compliance_audit_log',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='saveddownload',
            index=models.Index(fields=['user', 'track'], name='downloads_s_user_id_c07d96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offlinelibraryitem',
            unique_together={('user', 'track', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='complianceauditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='downloads_c_event_t_dcbbb7_idx'),
        ),
    ]
