# Generated by Django 4.2.30 on 2026-05-13 23:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('kind', models.CharField(choices=[('partner_catalog', 'Partner catalog API'), ('rights_holder_portal', 'Rights-holder portal'), ('user_owned_file', 'User-owned upload (creator flow)'), ('other_verified', 'Other verified legal source')], default='partner_catalog', max_length=32)),
                ('base_url', models.URLField(blank=True, max_length=500)),
                ('is_verified_partner', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'licensing_legal_source',
            },
        ),
        migrations.CreateModel(
            name='MusicLicense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'licensing_music_license',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='LicensedTrackSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_track_id', models.CharField(blank=True, max_length=255)),
                ('canonical_reference_url', models.URLField(blank=True, help_text='Human-readable reference on partner site (not a rip target).', max_length=800)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('legal_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licensed_tracks', to='licensing.legalsource')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licensed_track_sources', to='licensing.musiclicense')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licensed_sources', to='catalog.track')),
            ],
            options={
                'db_table': 'licensing_licensed_track_source',
                'unique_together': {('track', 'legal_source', 'partner_track_id')},
            },
        ),
        migrations.CreateModel(
            name='DownloadPermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allows_download', models.BooleanField(db_index=True, default=False)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_bitrate_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('licensed_track_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='download_permission', to='licensing.licensedtracksource')),
                ('requires_subscription_plan', models.ForeignKey(blank=True, help_text='If set, user must have active subscription at or above this tier.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_permissions', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'licensing_download_permission',
            },
        ),
    ]
