# Generated by Django 4.2.30 on 2026-05-13 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('backend_kind', models.CharField(choices=[('s3', 'Amazon S3'), ('gcs', 'Google Cloud Storage'), ('azure', 'Azure Blob'), ('other', 'Other')], default='s3', max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'storage_provider',
            },
        ),
        migrations.CreateModel(
            name='ManagedStorageObject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(db_index=True, max_length=1024)),
                ('bucket_name', models.CharField(blank=True, max_length=255)),
                ('media_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=128)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_objects', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objects', to='storage_integration.storageprovider')),
            ],
            options={
                'db_table': 'storage_managed_object',
                'unique_together': {('provider', 'object_key')},
            },
        ),
    ]
