# Generated by Django 4.2.30 on 2026-05-13 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinkMetadata',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_url', models.URLField(max_length=800)),
                ('normalized_url', models.URLField(blank=True, max_length=800)),
                ('platform', models.CharField(choices=[('unknown', 'Unknown'), ('partner', 'Verified partner share'), ('other', 'Other')], db_index=True, default='unknown', max_length=32)),
                ('detected_title', models.CharField(blank=True, max_length=255)),
                ('detected_artist', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_resolutions', to='catalog.track')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_link_metadata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_metadata_link',
                'indexes': [models.Index(fields=['normalized_url'], name='social_meta_normali_d38ed1_idx')],
            },
        ),
    ]
