# Generated by Django 4.2.30 on 2026-05-13 23:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('official_website', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'catalog_artist',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'db_table': 'catalog_genre',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.artist')),
            ],
            options={
                'db_table': 'catalog_album',
                'ordering': ('-release_date', 'title'),
                'unique_together': {('artist', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('isrc', models.CharField(blank=True, db_index=True, max_length=15)),
                ('explicit', models.BooleanField(default=False)),
                ('preview_stream_url', models.URLField(blank=True, help_text='Legal preview URL from a licensed partner only.', max_length=800)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='catalog.album')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_on_tracks', to='catalog.artist')),
                ('genres', models.ManyToManyField(blank=True, related_name='tracks', to='catalog.genre')),
                ('primary_artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_tracks', to='catalog.artist')),
            ],
            options={
                'db_table': 'catalog_track',
                'ordering': ('title',),
                'unique_together': {('primary_artist', 'slug')},
            },
        ),
    ]
