# Generated by Django 4.2.30 on 2026-05-13 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecognitionPrepJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('fingerprint_handle', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('input_storage_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_prep_jobs', to='storage_integration.managedstorageobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_prep_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_services_recognition_prep_job',
            },
        ),
        migrations.CreateModel(
            name='AIMoodDiscoverySession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood_label', models.CharField(blank=True, max_length=64)),
                ('mood_vector', models.JSONField(blank=True, default=dict)),
                ('matched_track_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('provider_job_id', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_services_mood_session',
            },
        ),
    ]
